language: c
os: 
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew update; brew install pcre; fi
sudo:
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then true; else false; fi
script: make && make check
compiler:
  - clang
  - gcc
